group: travis_latest
language: python
cache: pip
matrix:
  include:
    - python: 3.7
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
install:
  - python setup.py install
  - pip install flake8
before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --quiet
script:
  # Help message.
  - xsrfprobe --version
  - xsrfprobe --help
  - xsrfprobe -u http://www.webscantest.com --crawl --timeout 5 --max-chars 3 --quiet
  - xsrfprobe -u http://www.webscantest.com/csrf/csrfpost.php --timeout 10 --random-agent
  - xsrfprobe -u http://www.webscantest.com/csrf/token.php --timeout 15 --delay 2 --display
notifications:
  on_success: change
  on_failure: change  # `always` will be the setting once code changes slow down
