#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# -:-:-:-:-:-:-::-:-:#
#    XSRF Probe     #
# -:-:-:-:-:-:-::-:-:#

# Author: 0xInfection
# This module requires XSRFProbe
# https://github.com/0xInfection/XSRFProbe

import stringdist
import itertools
import time
import logging

from modules.Entropy import calcEntropy
from core.utils import sameSequence, byteString
from files.discovered import REQUEST_TOKENS
from core.logger import VulnLogger, NovulLogger

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger("Analysis")

def Analysis():
    """
    The main idea behind this is to observe and analyse
           the patterns in which the CSRF tokens
                  are generated by server.
    """
    ctr = 0  # Counter variable set to 0
    # Checking if the no of tokens is greater than 1
    if len(REQUEST_TOKENS) > 1:
        logger.info("\n+--------------+")
        logger.info("|   Analysis   |")
        logger.info("+--------------+\n")
        logger.info("Proceeding with post-scan analysis of tokens gathered...")
        logger.info("A total of %s tokens were discovered during the scan", len(REQUEST_TOKENS))

        for tokenx1, tokenx2 in itertools.combinations(REQUEST_TOKENS, 2):
            try:
                logger.info("Analyzing 2 Anti-CSRF Tokens from gathered requests...")
                logger.info("[+] First Token: %s", tokenx1)
                logger.info("[+] Shannon Entropy: %s", calcEntropy(tokenx1))
                logger.info("[+] Second Token: %s", tokenx2)
                logger.info("[+] Shannon Entropy: %s", calcEntropy(tokenx2))

                # Calculating the edit distance via Damerau Levenshtein algorithm
                m = stringdist.rdlevenshtein(tokenx1, tokenx2)
                logger.info("[+] Edit Distance Calculated: %s%%", m)

                # Detecting the alignment ratio
                n = stringdist.rdlevenshtein_norm(tokenx1, tokenx2)
                logger.info("[+] Alignment Ratio Calculated: %s", n)

                if len(tokenx1) == len(tokenx2):
                    logger.info("Token length is the same: Each %s bytes", len(byteString(tokenx1)))
                else:
                    logger.info(
                        "Token length is different: By %s bytes",
                        len(byteString(tokenx1)) - len(byteString(tokenx2))
                    )

                time.sleep(0.5)

                p = sameSequence(tokenx1, tokenx2)
                tokenx01 = tokenx1.replace(p, "")
                tokenx02 = tokenx2.replace(p, "")

                if n == 0.5 or m == len(tokenx1) / 2:
                    logger.warning("Tokens are composed of 2 parts (one static and one dynamic)...")
                    logger.info("Static Part: %s | Length: %s", p, len(p))
                    logger.info("Dynamic Part of Token 0x1: %s | Length: %s", tokenx01, len(tokenx01))
                    logger.info("Dynamic Part of Token 0x2: %s | Length: %s", tokenx02, len(tokenx02))

                    if len(tokenx1) / 2 <= 6:
                        logger.error("Post-Analysis reveals that token might be VULNERABLE")
                        logger.info("Possible CSRF Vulnerability Detected!")
                        logger.info("[!] Vulnerability Type: Weak Dynamic Part of Tokens")
                        logger.info("Tokens can easily be Forged by Bruteforcing/Guessing!")
                        VulnLogger(
                            "Analysis",
                            "Tokens can easily be Forged by Bruteforcing/Guessing.",
                            "[i] Token 1: " + tokenx1 + "\n[i] Token 2: " + tokenx2,
                        )
                elif n < 0.5 or m < len(tokenx1) / 2:
                    logger.warning("Token distance is less than 0.5!")
                    logger.info("Static Part: %s | Length: %s", p, len(p))
                    logger.info("Dynamic Part of Token 0x1: %s | Length: %s", tokenx01, len(tokenx01))
                    logger.info("Dynamic Part of Token 0x2: %s | Length: %s", tokenx02, len(tokenx02))

                    VulnLogger(
                        "Analysis",
                        "Tokens can easily be Forged by Bruteforcing/Guessing.",
                        "[i] Token 1: " + tokenx1 + "\n[i] Token 2: " + tokenx2,
                    )
                else:
                    logger.info("Token distance is greater than 0.5!")
                    logger.info("Static Part: %s | Length: %s", p, len(p))
                    logger.info("Dynamic Part of Token 0x1: %s | Length: %s", tokenx01, len(tokenx01))
                    logger.info("Dynamic Part of Token 0x2: %s | Length: %s", tokenx02, len(tokenx02))

                    NovulLogger(
                        "Analysis", "Tokens cannot be Forged by Bruteforcing/Guessing."
                    )

                time.sleep(1)
            except KeyboardInterrupt:
                ctr += 1
                continue

        logger.info("Post-Scan Analysis Completed!")